# 개발용 MySQL 설정
spring.datasource.url=jdbc:mysql://localhost:3306/dietmall
spring.datasource.username=dietmall_app
spring.datasource.password=${DB_PASSWORD}

# 개발용 JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 개발용 업로드 파일 저장 위치
app.upload-dir=uploads

# 식단 사진 업로드 크기 제한
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=21MB