spring.application.name=dietmall

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/dietmall
spring.datasource.username=dietmall_app
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=1209600000